### ISSUE TITLE
Port stairs functions to TypeScript for use with Babylonjs

### ISSUE THREAD

**Issue by LukeTOBrien** [blackears/blenderStairs#1]
Hello there,

I have started working on a project with [Babylonjs](https://www.babylonjs.com/) with the intent of releasing it as an open source project when finished.  
I was directed to your repo because I am interested in creating architecture and it seems that your Blender addon is use by members of the forum.  
I have created a [stairs function](https://www.babylonjs-playground.com/#12PDGR) but I think a curved stairs function would be a little trickier.

I was wondering have you ever used Babylonjs and would you be interested in trying to create a curved stairs function? 
I have been looking at the code for [kitfoxStairsCurved.py](https://github.com/blackears/blenderStairs/blob/master/operators/kitfoxStairsCurved.py) but it's not a straight port.

**Comment by blackears** [comment]
I've not used Babylon.js before, but I have used Javascript.  Porting to Babylon might be a good idea.  From their website, this seems to be a WebGL library like three.js?

**Comment by LukeTOBrien** [comment]
Yes, Babylonjs is an alternative libray to Threejs, they both are APIs used to created WebGL graphics, but Babylonjs has more features and better documentation (Microsoft puts their weight behind it).  

Looking at your code I beleive we could [Create a custom mesh](https://doc.babylonjs.com/divingDeeper/mesh/creation/custom/custom), although the [VertexData class](https://doc.babylonjs.com/typedoc/classes/babylon.vertexdata) use vertices and indices not vertices and faces, so the returned object will need to be:

```js
return {
  "vertices": ...,
  "Indices": ...,
  "uvs": ...
}
```

instead of:

```python
return verts, faces, uvs
```

**Comment by blackears** [comment]
I've written a port.  You can find it at https://github.com/blackears/babylonStairs/blob/main/README.md

**Comment by LukeTOBrien** [comment]
woaw, that was quick, thanks!  
I will be sure to tell every one about it!

**Comment by blackears** [comment]
Closing this.  If there are any problems with the port, please file an issue on that page.
