### ISSUE TITLE
Does not work for Blender 3.0?

### ISSUE THREAD

**Issue by XekriRedmane** [blackears/blenderStairs#3]
I downloaded the zip of the repo, installed it, got this message:

Modules Installed () from 'G:\\...\\Blender files\\plugins\\blenderStairs-master.zip' into 'C:\\Users\\...\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'

but the plugin does not appear in the list.

**Comment by blackears** [comment]
It should be there and look something like this:
![image](https://user-images.githubusercontent.com/6724608/154891088-a994f0d7-ad18-48cf-a64b-b908075ccaee.png)


If you do a search and still can't find it, please make sure it has been copied into your blender scripts addons folder (on Windows, something like C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.0\scripts/addons/stairs).  If you are still having trouble, please open the console window and see if any error messages have been printed there and if so let me know what they are.

**Comment by XekriRedmane** [comment]
I have C:\Users\username\AppData\Roaming\Blender
Foundation\Blender\3.0\scripts\addons\blenderStairs-master, which contains
the repo. There are no error messages on the console. And there is nothing
listed under "stairs" for the addons.

[image: image.png]

Is it possible that the instructions to download the zip of the repo and
install that, doesn't work? I see in your path you have
scripts/addons/stairs/__init__.py. Maybe the source dir of the repo needs
to be renamed to stairs, and that dir put into addons?

Yes, that was the problem. You might need to update your instructions on
how to install from github :<

**Comment by blackears** [comment]
The releases are distributed in an archive called stairs.zip.  I'm guessing you checked out the repo and tried to install that rather than build a release with the make file?

**Comment by XekriRedmane** [comment]
Yep. Absent any other instructions, I had to interpret "To install,
download this archive as a .zip file." There aren't any instructions about
building a release.

**Comment by blackears** [comment]
I've added some build instructions to the main page.  Hopefully this clears things up.  Please reopen if you are still having problems.
